baseURL = 'https://lyonef.com/'
languageCode = 'en-us'
title = 'Lyon Energy Futures'
googleAnalytics = 'G-M1F0R20E3L'

[permalinks]
  blog = '/:year/:month/:title/'

[markup.goldmark.renderer]
    unsafe= true

[params]

title = 'Lyon Energy Futures - Are You Ready'
author = 'Richard Lyon'
description = """
We are an independent research and business intelligence company, equipping clients with data and \
insights that power better decision making."""
opening_blurb = """
Our lives literally depend on cheap energy. Where it comes from, and how it is changing, should be \
taught at school alongside reading, writing, and arithmetic. Until now, we've never had to understand it. Now, we \
can't afford not to. And now, <a href="#" class="font-semibold text-orange-400">you can</a>."""
twitter_handle = "@LyonEnergyFtrs"
convertkit_id = 3704941

twitter_cards = true
images = ['/img/logo-200x200.png']

[[params.services]]
    supertitle = 'Training'
    title = 'Creating value through deep understanding'
    blurb = """
        Utility classes help you work within the constraints of a system instead of littering your 
        stylesheets with arbitrary values. They make it easy to be consistent with color choices, spacing, 
        typography, shadows, and everything else that makes up a well-engineered design system.
    """
    url = '#'
    color = 'indigo-500'
    weight = 1

[[params.services]]
    supertitle = 'Public speaking'
    title = 'Quantify risk and transfer knowledge' 
    blurb = """
            Econonomics blurb.
            """
    url = '#'
    color = 'pink-500'
    weight = 2

# [[params.services]]
#     supertitle = 'Project and Operations management'
#     title = 'Confident, technical, commercial' 
#     blurb = """
#             Services blurb.
#             """
#     url = '#'
#     color = 'sky-500'
#     weight = 3

[menu]

[[menu.main]]
    name = 'services'
    url = '#'
    weight = 1
[[menu.main]]
    name = 'blog'
    url = '/blog'
    weight = 2


