baseURL = 'https://lyonef.com/'
languageCode = 'en-us'
title = 'Lyon Energy Futures'

[params]
title = 'Lyon Energy Futures - Are You Ready'
author = 'Richard Lyon'
description = 'Lyon Energy Futures is an independent research and business intelligence company, equipping clients with data and insights that power better decision making.'